/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData food = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData account_balance = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_box = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData emo_happy = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData emo_thumbsup = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData emo_unhappy = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData camera_alt = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData basket = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData basket_1 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData basket_2 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData basket_3 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData basket_alt = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData basket_circled = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData progress_0 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData report_problem = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData notifications_paused = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData home_outline = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData home_1 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData sun_inv = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData appstore = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData skype_1 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData ebay = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData stripe = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData gmail = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData yahoo = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData windows = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData heart_circled = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData download_alt = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData attach = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData volume_off = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData volume_down = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData volume = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData volume_up = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData headphones = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData arrows_cw = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData cw_circled = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData cw = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData down_hand = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData left_hand = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData right_hand = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData up_hand = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData off = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData linkedin_1 = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData facebook_2 = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData skype_3 = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData glasses = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData attach_1 = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData key_1 = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData ie = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData doc = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData truck = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData tv = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData calendar_1 = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData params = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData picture_1 = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData comment_alt = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData lock_open = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData signal = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData attention = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData phone_outline = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData phone_1 = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData home_2 = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData town_hall = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData phone_2 = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData account_balance_wallet = const IconData(0xf008, fontFamily: _kFontFam);
  static const IconData download_1 = const IconData(0xf02e, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xf02f, fontFamily: _kFontFam);
  static const IconData phone_squared = const IconData(0xf098, fontFamily: _kFontFam);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData user_md = const IconData(0xf0f0, fontFamily: _kFontFam);
  static const IconData hospital = const IconData(0xf0f8, fontFamily: _kFontFam);
  static const IconData ambulance = const IconData(0xf0f9, fontFamily: _kFontFam);
  static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam);
  static const IconData taxi = const IconData(0xf1ba, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData hand_pointer_o = const IconData(0xf25a, fontFamily: _kFontFam);
  static const IconData hand_peace_o = const IconData(0xf25b, fontFamily: _kFontFam);
  static const IconData commenting_o = const IconData(0xf27b, fontFamily: _kFontFam);
  static const IconData facebook_1 = const IconData(0xf300, fontFamily: _kFontFam);
  static const IconData facebook_rect = const IconData(0xf301, fontFamily: _kFontFam);
  static const IconData twitter_bird = const IconData(0xf303, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData skype_2 = const IconData(0xf30b, fontFamily: _kFontFam);
  static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData linkedin_rect = const IconData(0xf31b, fontFamily: _kFontFam);
}
